DROP TABLE IF EXISTS ny_col_merge;
CREATE TABLE ny_col_merge (
    COLLISION_ID INTEGER,
    CRASHDATETIME DATE NOT NULL,
    BOROUGH TEXT,
    COUNTY TEXT,
    STATE TEXT,
    ZIPCODE TEXT,
    LATITUDE REAL,
    LONGITUDE REAL,
    VEHICLE_ID INTEGER,
    STATE_REGISTRATION TEXT,
    VEHICLE_CATEGORY TEXT,
    VEHICLE_YEAR INTEGER,
    DRIVER_LICENSE_STATUS TEXT,
    DRIVER_LICENSE_JURISDICTION TEXT,
    PRIMARY_CONTRIBUTING_FACTOR TEXT,
    PERSON_ID INTEGER,
    PERSON_TYPE TEXT,
    PERSON_ROLE TEXT,
    PERSON_AGE INTEGER,
    PERSON_SEX TEXT,
    PERSON_INJURY TEXT,
    SAFETY_EQUIPMENT TEXT
);

INSERT INTO ny_col_merge (
    COLLISION_ID, CRASHDATETIME, BOROUGH, COUNTY, STATE, ZIPCODE, LATITUDE, LONGITUDE,
    VEHICLE_ID, STATE_REGISTRATION, VEHICLE_CATEGORY, VEHICLE_YEAR, DRIVER_LICENSE_STATUS,
    DRIVER_LICENSE_JURISDICTION, PRIMARY_CONTRIBUTING_FACTOR, PERSON_ID, PERSON_TYPE, 
    PERSON_ROLE, PERSON_AGE, PERSON_SEX, PERSON_INJURY, SAFETY_EQUIPMENT
)
SELECT 
    CRASH_2NF.COLLISION_ID, CRASHDATETIME, BOROUGH, COUNTY, STATE, ZIPCODE, LATITUDE, LONGITUDE,
    VEHICLE_2NF.VEHICLE_ID, STATE_REGISTRATION, VEHICLE_CATEGORY, VEHICLE_YEAR, DRIVER_LICENSE_STATUS,
    DRIVER_LICENSE_JURISDICTION, PRIMARY_CONTRIBUTING_FACTOR, PERSON_ID, PERSON_TYPE, 
    PERSON_ROLE, PERSON_AGE, PERSON_SEX, PERSON_INJURY, SAFETY_EQUIPMENT
FROM CRASH_2NF 
LEFT JOIN VEHICLE_2NF  ON CRASH_2NF.COLLISION_ID = VEHICLE_2NF.COLLISION_ID
LEFT JOIN PERSON_2NF  ON (PERSON_2NF.COLLISION_ID = CRASH_2NF.COLLISION_ID AND (PERSON_2NF.VEHICLE_ID IS NULL OR PERSON_2NF.VEHICLE_ID IN (SELECT VEHICLE_ID FROM VEHICLE_2NF)));
