DROP TABLE IF EXISTS VEHICLE_1NF;

CREATE TABLE VEHICLE_1NF
(
	VEHICLE_ID INTEGER PRIMARY KEY,
    COLLISION_ID INTEGER,
    STATE_REGISTRATION TEXT,
    VEHICLE_CATEGORY TEXT,
    VEHICLE_YEAR INTEGER,
    DRIVER_LICENSE_STATUS TEXT,
    DRIVER_LICENSE_JURISDICTION TEXT,
    PRIMARY_CONTRIBUTING_FACTOR TEXT 
);

INSERT INTO VEHICLE_1NF 
(
  COLLISION_ID,
  STATE_REGISTRATION,
  VEHICLE_CATEGORY,
  VEHICLE_YEAR,
  DRIVER_LICENSE_STATUS,
  DRIVER_LICENSE_JURISDICTION,
  PRIMARY_CONTRIBUTING_FACTOR
)


SELECT
  COLLISION_ID,
  STATE_REGISTRATION,
  VEHICLE_CATEGORY,
  VEHICLE_YEAR,
  DRIVER_LICENSE_STATUS,
  DRIVER_LICENSE_JURISDICTION,
  CASE WHEN CONTRIBUTING_FACTOR_1 IS NULL THEN 'Unspecified' ELSE CONTRIBUTING_FACTOR_1 END AS PRIMARY_CONTRIBUTING_FACTOR
FROM
VEHICLE_0NF
INNER JOIN VEHICLE_TYPE_TO_CATEGORY ON VEHICLE_0NF.VEHICLE_TYPE = VEHICLE_TYPE_TO_CATEGORY.VEHICLE_TYPE;